/**
 * Type definitions for database.json
 *
 * This file types the structure of the pre-built database.json file
 * generated by scripts/build-data.mjs
 */

import type {
  Expert,
  Organization,
  Estimate,
  Crux,
  GlossaryTerm,
  Entity,
  Resource,
} from './schema';

/**
 * Backlink entry - represents an entity that links to another entity
 */
export interface BacklinkEntry {
  id: string;
  type: string;
  title: string;
  relationship?: string;
}

/**
 * Tag index entry - represents an entity with a specific tag
 */
export interface TagIndexEntry {
  id: string;
  type: string;
  title: string;
}

/**
 * Recently updated entry
 */
export interface RecentlyUpdatedEntry {
  id: string;
  type: string;
  title: string;
  lastUpdated: string;
}

/**
 * Most linked entry
 */
export interface MostLinkedEntry {
  id: string;
  type: string;
  title: string;
  backlinkCount: number;
}

/**
 * Tag count entry
 */
export interface TagCountEntry {
  tag: string;
  count: number;
}

/**
 * Statistics computed from entities
 */
export interface DatabaseStats {
  totalEntities: number;
  byType: Record<string, number>;
  bySeverity: Record<string, number>;
  byStatus: Record<string, number>;
  recentlyUpdated: RecentlyUpdatedEntry[];
  mostLinked: MostLinkedEntry[];
  topTags: TagCountEntry[];
  totalTags: number;
  withDescription: number;
  lastBuilt: string;
}

/**
 * Model ratings from frontmatter
 */
export interface ModelRatings {
  novelty?: number;
  rigor?: number;
  actionability?: number;
  completeness?: number;
}

/**
 * Structural metrics computed for pages
 * Note: This matches the PageMetrics interface in index.ts
 */
export interface PageMetrics {
  wordCount: number;
  tableCount: number;
  diagramCount: number;
  internalLinks: number;
  externalLinks: number;
  bulletRatio: number;
  sectionCount: number;
  hasOverview: boolean;
  structuralScore: number;
}

/**
 * Page entry from pages registry
 */
export interface PageEntry {
  id: string;
  path: string;
  filePath: string;
  title: string;
  quality: number | null;
  importance: number | null;
  lastUpdated: string | null;
  llmSummary: string | null;
  description: string | null;
  ratings: ModelRatings | null;
  category: string;
  metrics: PageMetrics;
  suggestedQuality: number;
  wordCount: number;
  backlinkCount: number;
}

/**
 * Literature paper entry
 */
export interface LiteraturePaper {
  title: string;
  authors?: string[];
  year?: number;
  link?: string;
}

/**
 * Literature category
 */
export interface LiteratureCategory {
  name: string;
  papers?: LiteraturePaper[];
}

/**
 * Literature data structure
 */
export interface LiteratureData {
  categories: LiteratureCategory[];
}

/**
 * Funder entry
 */
export interface FunderEntry {
  id: string;
  name: string;
  type?: string;
  website?: string;
  focus?: string[];
}

/**
 * The complete database structure
 */
export interface Database {
  // Core data from YAML files
  experts: Expert[];
  organizations: Organization[];
  estimates: Estimate[];
  cruxes: Crux[];
  glossary: GlossaryTerm[];
  entities: Entity[];
  literature: LiteratureData;
  funders: FunderEntry[];
  resources: Resource[];

  // Computed/derived data
  backlinks: Record<string, BacklinkEntry[]>;
  tagIndex: Record<string, TagIndexEntry[]>;
  stats: DatabaseStats;
  pathRegistry: Record<string, string>;
  pages: PageEntry[];
}
